"""
Script cập nhật TOÀN BỘ meaning và advice - ĐÃ XÁC MINH BẰNG ẢNH THỰC TẾ TRONG DATASET
"""
import pandas as pd
import os

METADATA_PATH = "d:/gtvn/data/metadata.csv"

# SỬA LẠI DỰA TRÊN ẢNH THỰC TẾ - ĐÃ KIỂM CHỨNG
SIGN_DATA = {
    # === BIỂN PHỤ (DP) ===
    "DP.127a": ("Biển phụ khoảng cách đến đoạn nguy hiểm", "Chú ý khoảng cách đến đoạn đường nguy hiểm phía trước."),
    "DP.127b": ("Biển phụ phạm vi tác dụng của biển", "Chú ý phạm vi áp dụng của biển báo chính phía trên."),
    "DP.127c": ("Biển phụ khoảng cách lặp lại", "Biển phụ nhắc lại khoảng cách, chú ý biển chính."),
    "DP.133": ("Biển phụ loại xe bị cấm", "Xem kỹ biển phụ để biết loại xe nào bị cấm."),
    "DP.134": ("Biển phụ khoảng cách đến đối tượng báo hiệu", "Chú ý khoảng cách đến đối tượng trên biển chính."),
    "DP.135": ("Biển phụ hướng tác dụng của biển", "Chú ý hướng áp dụng của biển báo chính."),

    # === BIỂN CHỈ DẪN (I) ===
    "I.401": ("Bắt đầu đường ưu tiên", "Xe trên đường này được quyền đi trước tại nơi giao nhau không đèn tín hiệu."),
    "I.402": ("Hết đoạn đường ưu tiên", "Hết quyền ưu tiên, nhường đường theo quy tắc thông thường."),
    "I.405a": ("Đường cụt phía trước", "Đường phía trước không có lối thoát, chuẩn bị quay đầu."),
    "I.405b": ("Đường cụt phía bên phải", "Đường nhánh bên phải là đường cụt."),
    "I.405c": ("Đường cụt phía bên trái", "Đường nhánh bên trái là đường cụt."),
    "I.406": ("Được ưu tiên qua đường hẹp", "Bạn được ưu tiên đi trước trên đoạn đường hẹp, nhưng vẫn phải quan sát."),
    "I.407a": ("Đường một chiều đi thẳng", "Đường chỉ một chiều, không được đi ngược lại."),
    "I.407b": ("Đường một chiều sang phải", "Đường chỉ cho phép đi sang phải."),
    "I.407c": ("Đường một chiều sang trái", "Đường chỉ cho phép đi sang trái."),
    "I.408": ("Nơi đỗ xe", "Khu vực cho phép đỗ xe, đỗ đúng nơi quy định."),
    "I.408a": ("Nơi đỗ xe một phần trên hè phố", "Nơi được phép đỗ một phần xe lên hè phố rộng."),
    "I.409": ("Chỗ quay xe (quay đầu chữ U)", "Cho phép quay đầu xe tại vị trí này."),
    "I.410": ("Khu vực quay xe", "Khu vực cho phép quay đầu xe, quan sát kỹ."),
    "I.413a": ("Làn đường dành cho ô tô khách", "Phía trước có làn đường dành riêng cho ô tô khách."),
    "I.413b": ("Làn đường dành cho ô tô khách rẽ phải", "Rẽ phải để vào làn dành cho ô tô khách."),
    "I.413c": ("Làn đường dành cho ô tô khách rẽ trái", "Rẽ trái để vào làn dành cho ô tô khách."),
    "I.414a": ("Chỉ hướng đường phía trước", "Biển chỉ hướng đi đến các địa danh phía trước."),
    "I.414b": ("Chỉ hướng đường rẽ phải", "Biển chỉ hướng rẽ phải đến các địa danh."),
    "I.414c": ("Chỉ hướng đường rẽ trái", "Biển chỉ hướng rẽ trái đến các địa danh."),
    "I.414d": ("Chỉ hướng đường tổng hợp", "Biển chỉ hướng nhiều hướng đi khác nhau."),
    "I.415": ("Nơi đỗ xe taxi", "Khu vực dành riêng cho taxi dừng đón trả khách."),
    "I.416": ("Bến phà", "Phía trước có bến phà, giảm tốc và xếp hàng chờ."),
    "I.417a": ("Bến xe (trạm xe buýt, nhà ga) phía trước", "Phía trước có bến xe hoặc nhà ga."),
    "I.417b": ("Bến xe rẽ phải", "Bến xe nằm bên phải, rẽ phải để vào."),
    "I.417c": ("Bến xe rẽ trái", "Bến xe nằm bên trái, rẽ trái để vào."),
    "I.418": ("Bãi đỗ xe có thu phí", "Khu vực đỗ xe có thu phí, chuẩn bị thanh toán."),
    "I.419a": ("Bệnh viện phía trước", "Phía trước có bệnh viện, giảm tốc và không bấm còi."),
    "I.419b": ("Bệnh viện rẽ phải", "Bệnh viện bên phải, rẽ phải để đến."),
    "I.422a": ("Trạm cấp cứu phía trước", "Phía trước có trạm cấp cứu."),
    "I.422b": ("Trạm cấp cứu rẽ phải", "Trạm cấp cứu bên phải."),
    "I.423a": ("Trạm xăng dầu phía trước", "Phía trước có trạm xăng, giảm tốc khi vào."),
    "I.423b": ("Trạm xăng dầu rẽ phải", "Trạm xăng bên phải."),
    "I.423c": ("Trạm xăng dầu rẽ trái", "Trạm xăng bên trái."),
    "I.424a": ("Khách sạn, nhà nghỉ phía trước", "Phía trước có nơi lưu trú."),
    "I.424b": ("Khách sạn, nhà nghỉ rẽ phải", "Nơi lưu trú bên phải."),
    "I.424c": ("Khách sạn, nhà nghỉ rẽ trái", "Nơi lưu trú bên trái."),
    "I.424d": ("Nhà hàng phía trước", "Phía trước có nhà hàng."),
    "I.425": ("Khu cắm trại", "Phía trước có khu cắm trại."),
    "I.426": ("Trạm sửa chữa ô tô phía trước", "Phía trước có trạm sửa xe."),
    "I.427a": ("Trạm sửa chữa ô tô rẽ trái", "Trạm sửa xe bên trái."),
    "I.427b": ("Trạm sửa chữa ô tô rẽ phải", "Trạm sửa xe bên phải."),
    "I.428a": ("Điện thoại công cộng", "Phía trước có trạm điện thoại."),
    "I.429": ("Nơi rửa xe", "Phía trước có dịch vụ rửa xe."),
    "I.430": ("Khu vệ sinh công cộng", "Phía trước có nhà vệ sinh công cộng."),
    "I.431": ("Bắt đầu đường cao tốc", "Bắt đầu vào đường cao tốc, tuân thủ tốc độ quy định."),
    "I.432": ("Hết đường cao tốc", "Hết đoạn cao tốc, giảm tốc."),
    "I.433a": ("Chỉ dẫn làn đường trên đường nhiều làn", "Đi đúng làn đường được chỉ dẫn."),
    "I.433b": ("Chỉ dẫn làn đường 2 làn cùng chiều", "Chọn làn phù hợp theo hướng đi."),
    "I.433c": ("Chỉ dẫn làn đường 3 làn cùng chiều", "Chọn làn phù hợp, làn trái cho xe vượt."),
    "I.433d": ("Chỉ dẫn làn đường 4 làn cùng chiều", "Đi đúng làn, quan sát biển phụ."),
    "I.433e": ("Chỉ dẫn làn đường trên cao tốc", "Tuân thủ quy định làn trên đường cao tốc."),
    "I.434a": ("Bắt đầu làn xe dành riêng", "Bắt đầu đoạn có làn dành riêng, không lấn làn."),
    "I.434b": ("Hết làn xe dành riêng", "Hết đoạn có làn riêng."),
    "I.435": ("Cầu vượt liên thông", "Phía trước có cầu vượt, chọn nhánh rẽ phù hợp."),
    "I.436": ("Đường trên cao", "Phía trước có đường trên cao, chú ý lối lên."),
    "I.437": ("Hầm chui dân sinh", "Phía trước có hầm chui, giảm tốc và bật đèn."),
    "I.439": ("Trạm thu phí đường bộ", "Phía trước có trạm thu phí, chuẩn bị thanh toán."),
    "I.440": ("Đường cứu nạn", "Lối vào đường cứu nạn dành cho xe mất phanh."),
    "I.441a": ("Chỉ dẫn tên đường phố", "Quan sát tên đường để xác định vị trí."),
    "I.441b": ("Chỉ dẫn tên đường phố rẽ", "Đường rẽ phía trước mang tên trên biển."),
    "I.441c": ("Chỉ dẫn tên đường tại ngã tư", "Quan sát biển chỉ dẫn tên đường tại ngã tư."),
    "I.442": ("Chỉ dẫn tên cầu hoặc sông", "Bạn đang đi qua cầu hoặc sông trên biển."),
    "I.443": ("Cột km (số kilomet)", "Biển báo khoảng cách km trên quốc lộ."),
    "I.444a": ("Địa giới tỉnh, thành phố", "Bạn đang đi vào ranh giới tỉnh/thành phố mới."),
    "I.444b": ("Địa giới quận, huyện", "Bạn đang đi vào ranh giới quận/huyện mới."),
    "I.444c": ("Địa giới xã, phường", "Bạn đang đi vào ranh giới xã/phường mới."),
    "I.444d": ("Bắt đầu khu đô thị", "Bắt đầu khu đô thị, giảm tốc."),
    "I.444e": ("Hết khu đô thị", "Hết khu đô thị, có thể tăng tốc."),
    "I.444f": ("Địa danh du lịch", "Phía trước có địa danh du lịch."),
    "I.444g": ("Địa danh lịch sử", "Phía trước có khu di tích lịch sử."),
    "I.444h": ("Địa danh văn hóa", "Phía trước có khu văn hóa."),
    "I.444i": ("Khu công nghiệp", "Phía trước có khu công nghiệp, chú ý xe tải lớn."),
    "I.444j": ("Khu kinh tế", "Phía trước có khu kinh tế."),
    "I.444k": ("Cửa khẩu quốc tế", "Gần cửa khẩu, chuẩn bị giấy tờ."),
    "I.444l": ("Sân bay", "Phía trước có sân bay."),
    "I.444m": ("Cảng biển", "Phía trước có cảng biển, chú ý xe container."),
    "I.445a": ("Chỉ dẫn khoảng cách đến các địa danh", "Tham khảo khoảng cách để lên kế hoạch hành trình."),
    "I.445b": ("Chỉ dẫn khoảng cách rẽ phải", "Khoảng cách đến điểm rẽ phải."),
    "I.445c": ("Chỉ dẫn khoảng cách rẽ trái", "Khoảng cách đến điểm rẽ trái."),
    "I.445d": ("Chỉ dẫn hướng và khoảng cách rẽ phải", "Đi rẽ phải với khoảng cách trên biển."),
    "I.445e": ("Chỉ dẫn hướng và khoảng cách rẽ trái", "Đi rẽ trái với khoảng cách trên biển."),
    "I.445f": ("Chỉ dẫn khoảng cách thẳng và rẽ", "Xem biển để chọn hướng."),
    "I.445g": ("Chỉ dẫn khoảng cách rẽ trái và phải", "Xem biển để quyết định rẽ."),
    "I.445h": ("Chỉ dẫn khoảng cách phức hợp", "Đọc kỹ biển chỉ dẫn nhiều hướng."),
    "I.446": ("Sơ đồ chỉ dẫn đường trước ngã tư", "Quan sát sơ đồ ngã tư để chọn hướng."),
    "I.447a": ("Sơ đồ tuyến đường liên tỉnh", "Đọc sơ đồ tuyến đường liên tỉnh."),
    "I.447b": ("Sơ đồ tuyến đường nội tỉnh", "Đọc sơ đồ tuyến đường nội tỉnh."),
    "I.447c": ("Sơ đồ đường vòng tránh", "Đi đường vòng tránh nếu đường chính tắc."),
    "I.447d": ("Sơ đồ tuyến đường cao tốc", "Xem sơ đồ chọn lối vào cao tốc."),
    "I.448": ("Số hiệu quốc lộ", "Ghi nhớ số hiệu quốc lộ."),
    "I.449": ("Số hiệu đường tỉnh", "Ghi nhớ số hiệu đường tỉnh."),

    # === BIỂN CẤM (P) - ĐÃ KIỂM CHỨNG BẰNG ẢNH ===
    "P.101": ("Đường cấm (cấm mọi phương tiện cả 2 hướng)", "Tuyệt đối không đi vào, vi phạm bị xử phạt nặng."),
    "P.102": ("Cấm đi ngược chiều", "Không được đi vào theo chiều đặt biển. Đây là đường một chiều."),
    "P.103a": ("Cấm ô tô", "Cấm tất cả ô tô, xe máy ba bánh có thùng. Xe máy 2 bánh vẫn được."),
    "P.103b": ("Cấm ô tô rẽ phải", "Ô tô không được rẽ phải. Xe máy 2 bánh vẫn được rẽ."),
    "P.103c": ("Cấm ô tô rẽ trái", "Ô tô không được rẽ trái. Xe máy 2 bánh vẫn được rẽ."),
    "P.104": ("Cấm xe mô tô", "Cấm mô tô đi vào. Không cấm xe gắn máy dưới 50cc."),
    "P.105": ("Cấm ô tô và xe mô tô", "Cấm cả ô tô lẫn mô tô. Chỉ xe đạp và người đi bộ được qua."),
    "P.106a": ("Cấm ô tô tải có tải trọng vượt quy định", "Xe tải quá tải trọng trên biển không được qua."),
    "P.106b": ("Cấm ô tô tải trên 2.5 tấn", "Xe tải quá 2.5 tấn không được qua."),
    "P.106c": ("Cấm ô tô tải trên 3.5 tấn", "Xe tải quá 3.5 tấn không được qua."),
    "P.107": ("Cấm ô tô khách và ô tô tải", "Xe tải và xe khách không được đi vào."),
    "P.107a": ("Cấm ô tô khách", "Xe chở khách không được đi qua."),
    "P.107b": ("Cấm xe taxi", "Xe taxi không được đi qua."),
    "P.108": ("Cấm xe kéo rơ-moóc", "Xe kéo rơ-moóc, sơ-mi rơ-moóc không được qua."),
    "P.108a": ("Cấm xe kéo sơ-mi rơ-moóc", "Xe đầu kéo sơ-mi rơ-moóc không được qua."),
    "P.109": ("Cấm máy kéo", "Cấm tất cả máy kéo (cả bánh hơi và bánh xích)."),
    "P.110a": ("Cấm xe đạp", "Xe đạp không được lưu thông. Có thể dắt bộ."),
    "P.110b": ("Cấm xe đạp thồ", "Xe đạp chở hàng (đạp thồ) không được qua."),
    "P.111a": ("Cấm xe gắn máy", "Cấm xe gắn máy dưới 50cc đi vào."),
    "P.111b": ("Cấm xe ba bánh có động cơ (xe lam)", "Xe lam, xích lô máy không được qua."),
    "P.111c": ("Cấm xe ba bánh có động cơ (dạng khác)", "Xe ba bánh có động cơ loại khác không được qua."),
    "P.111d": ("Cấm xe ba bánh không có động cơ (xích lô đạp)", "Xích lô, xe lôi đạp không được lưu thông."),
    "P.112": ("Cấm người đi bộ", "Người đi bộ không được đi trên đường này, dùng cầu vượt hoặc hầm."),
    "P.113": ("Cấm xe người kéo, đẩy", "Xe kéo, đẩy bằng tay không được đi qua."),
    "P.114": ("Cấm xe súc vật kéo", "Xe do súc vật kéo không được đi qua."),
    "P.115": ("Hạn chế trọng tải toàn bộ xe", "Xe nặng hơn trị số trên biển không được qua."),
    "P.116": ("Hạn chế tải trọng trên trục xe", "Xe có tải trọng trục vượt trị số không được qua."),
    "P.117": ("Hạn chế chiều cao xe", "Xe cao hơn trị số trên biển không được qua (hầm, gầm cầu)."),
    "P.118": ("Hạn chế chiều ngang xe (chiều rộng)", "Xe rộng hơn trị số trên biển không được qua."),
    "P.119": ("Hạn chế chiều dài xe", "Xe dài hơn trị số trên biển không được qua."),
    "P.120": ("Hạn chế chiều dài đoàn xe kéo moóc", "Đoàn xe dài hơn trị số trên biển không được qua."),
    "P.121": ("Cự ly tối thiểu giữa hai xe", "Giữ khoảng cách tối thiểu giữa hai xe theo trị số trên biển."),
    "P.123a": ("Cấm rẽ trái", "Không được rẽ trái, đi thẳng hoặc rẽ phải."),
    "P.123b": ("Cấm rẽ phải", "Không được rẽ phải, đi thẳng hoặc rẽ trái."),
    # P.124 - ĐÃ XÁC MINH BẰNG ẢNH THỰC TẾ
    "P.124a1": ("Cấm quay đầu xe (hướng trái)", "Không được quay đầu xe kiểu chữ U sang trái tại đây."),
    "P.124a2": ("Cấm quay đầu xe (hướng phải)", "Không được quay đầu xe kiểu chữ U sang phải tại đây."),
    "P.124b1": ("Cấm ô tô quay đầu xe (hướng trái)", "Ô tô không được quay đầu sang trái. Xe máy vẫn được."),
    "P.124b2": ("Cấm ô tô quay đầu xe (hướng phải)", "Ô tô không được quay đầu sang phải. Xe máy vẫn được."),
    "P.124c": ("Cấm rẽ trái và cấm quay đầu xe", "Không được rẽ trái và không được quay đầu tại đây."),
    "P.124d": ("Cấm rẽ phải và cấm quay đầu xe", "Không được rẽ phải và không được quay đầu tại đây."),
    "P.124e": ("Cấm ô tô rẽ trái và quay đầu xe", "Ô tô không được rẽ trái và quay đầu. Xe máy vẫn được."),
    "P.124f": ("Cấm ô tô rẽ phải và quay đầu xe", "Ô tô không được rẽ phải và quay đầu. Xe máy vẫn được."),
    # P.125-P.140 - ĐÃ KIỂM CHỨNG
    "P.125": ("Cấm vượt", "Không được vượt xe phía trước trên đoạn đường này."),
    "P.126": ("Cấm ô tô tải vượt", "Xe tải không được vượt xe khác trên đoạn đường này."),
    "P.127": ("Tốc độ tối đa cho phép", "Không vượt quá tốc độ ghi trên biển."),
    "P.127a": ("Tốc độ tối đa cho xe tải và xe khách", "Xe tải, xe khách không vượt quá tốc độ trên biển."),
    "P.127b": ("Tốc độ tối đa khi trời mưa", "Khi trời mưa, không vượt quá tốc độ trên biển."),
    "P.127c": ("Tốc độ tối đa cho riêng từng loại xe", "Mỗi loại xe có giới hạn tốc độ riêng trên biển."),
    "P.128": ("Cấm sử dụng còi", "Không bấm còi, khu vực yên tĩnh."),
    "P.129": ("Kiểm tra (trạm kiểm tra)", "Bắt buộc dừng xe tại trạm kiểm tra phía trước."),
    "P.130": ("Cấm dừng xe và đỗ xe", "Tuyệt đối không dừng, không đỗ xe."),
    "P.131a": ("Cấm đỗ xe (ngày lẻ)", "Không đỗ xe vào ngày lẻ (1, 3, 5...) trong tháng."),
    "P.131b": ("Cấm đỗ xe (ngày chẵn)", "Không đỗ xe vào ngày chẵn (2, 4, 6...) trong tháng."),
    "P.131c": ("Cấm đỗ xe", "Không được đỗ xe, nhưng có thể dừng tạm."),
    "P.132": ("Nhường đường cho xe ngược chiều qua đường hẹp", "Phải nhường đường cho xe ngược chiều đi qua đoạn hẹp trước."),
    "P.136": ("Cấm đi ngược chiều (loại khác)", "Không được đi vào theo chiều đặt biển."),
    "P.137": ("Cấm rẽ trái và rẽ phải", "Không được rẽ trái hay rẽ phải, chỉ được đi thẳng."),
    "P.138": ("Cấm đi thẳng và rẽ trái", "Không được đi thẳng và rẽ trái, chỉ được rẽ phải."),
    "P.139": ("Cấm đi thẳng và rẽ phải", "Không được đi thẳng và rẽ phải, chỉ được rẽ trái."),
    "P.140": ("Cấm xe công nông", "Xe công nông và xe máy chuyên dùng tương tự không được qua."),

    # === BIỂN HIỆU LỆNH (R) - ĐÃ KIỂM CHỨNG ===
    "R.122": ("Dừng lại (STOP)", "Bắt buộc dừng xe hoàn toàn trước vạch, quan sát rồi mới đi."),
    "R.301a": ("Hướng đi phải theo: chỉ được đi thẳng", "Bắt buộc đi thẳng, không được rẽ."),
    "R.301b": ("Hướng đi phải theo: chỉ được rẽ phải", "Bắt buộc rẽ phải."),
    "R.301c": ("Hướng đi phải theo: chỉ được rẽ trái", "Bắt buộc rẽ trái."),
    "R.301d": ("Hướng đi phải theo: chỉ được rẽ phải (dạng khác)", "Bắt buộc rẽ phải tại nút giao."),
    "R.301e": ("Hướng đi phải theo: chỉ được rẽ trái (dạng khác)", "Bắt buộc rẽ trái tại nút giao."),
    "R.301f": ("Hướng đi phải theo: đi thẳng và rẽ phải", "Chỉ được đi thẳng hoặc rẽ phải."),
    "R.301g": ("Hướng đi phải theo: đi thẳng và rẽ trái", "Chỉ được đi thẳng hoặc rẽ trái."),
    "R.301h": ("Hướng đi phải theo: rẽ trái và rẽ phải", "Chỉ được rẽ trái hoặc phải, không đi thẳng."),
    "R.302a": ("Đi vòng sang phải qua chướng ngại vật", "Phải vòng sang phải qua chướng ngại vật."),
    "R.302b": ("Đi vòng sang trái qua chướng ngại vật", "Phải vòng sang trái qua chướng ngại vật."),
    "R.302c": ("Đi vòng qua chướng ngại vật (cả hai bên)", "Có thể vòng trái hoặc phải."),
    "R.303": ("Nơi giao nhau chạy theo vòng xuyến", "Đi theo vòng xuyến đúng chiều."),
    "R.304": ("Đường dành cho xe thô sơ và người đi bộ", "Đường chỉ cho xe đạp, xe thô sơ và người đi bộ."),
    "R.305": ("Đường dành cho người đi bộ", "Đường chỉ cho người đi bộ, xe không được vào."),
    "R.306": ("Tốc độ tối thiểu cho phép", "Phải đạt tốc độ tối thiểu trên biển."),
    "R.307": ("Hết tốc độ tối thiểu", "Hết yêu cầu tốc độ tối thiểu."),
    "R.308a": ("Tuyến đường có cầu vượt cắt qua (rẽ phải)", "Phía trước có cầu vượt, rẽ phải theo chỉ dẫn."),
    "R.308b": ("Tuyến đường có cầu vượt cắt qua (rẽ trái)", "Phía trước có cầu vượt, rẽ trái theo chỉ dẫn."),
    "R.309": ("Ấn còi (phải bấm còi)", "Bắt buộc bấm còi khi qua đoạn đường tầm nhìn hạn chế."),
    "R.310a": ("Hướng đi cho xe chở hàng nguy hiểm: rẽ phải", "Xe chở hàng nguy hiểm bắt buộc rẽ phải."),
    "R.310b": ("Hướng đi cho xe chở hàng nguy hiểm: rẽ trái", "Xe chở hàng nguy hiểm bắt buộc rẽ trái."),
    "R.310c": ("Hướng đi cho xe chở hàng nguy hiểm: đi thẳng", "Xe chở hàng nguy hiểm bắt buộc đi thẳng."),
    "R.403a": ("Hướng đi trên mỗi làn: rẽ trái và thẳng", "Chọn làn: rẽ trái hoặc đi thẳng."),
    "R.403b": ("Hướng đi trên mỗi làn: thẳng và rẽ phải", "Chọn làn: đi thẳng hoặc rẽ phải."),
    "R.403c": ("Hướng đi trên mỗi làn: trái, thẳng, phải", "Chọn đúng làn: trái, thẳng hoặc phải."),
    "R.403d": ("Hướng đi trên mỗi làn: rẽ trái và phải", "Chọn làn rẽ trái hoặc phải."),
    "R.403e": ("Hướng đi trên mỗi làn (5 dạng)", "Chọn đúng làn theo mũi tên chỉ dẫn."),
    "R.403f": ("Hướng đi trên mỗi làn (6 dạng)", "Chọn đúng làn theo hướng đi."),
    "R.403g": ("Hướng đi trên mỗi làn (7 dạng)", "Đọc kỹ mũi tên trên biển để chọn đúng làn."),
    "R.403h": ("Hướng đi trên mỗi làn (8 dạng)", "Quan sát mũi tên và chuyển làn đúng hướng từ xa."),
    "R.403k": ("Hướng đi trên mỗi làn (nhiều làn)", "Đọc kỹ chỉ dẫn làn đường và chọn từ xa."),
    "R.404a": ("Làn dành riêng cho xe buýt rẽ trái", "Làn này chỉ cho xe buýt, xe khác không vào."),
    "R.404b": ("Làn dành riêng cho xe buýt đi thẳng", "Làn xe buýt đi thẳng, xe khác không lấn."),
    "R.404c": ("Làn dành riêng cho xe buýt rẽ phải", "Làn cho xe buýt rẽ phải, xe khác dùng làn khác."),
    "R.404d": ("Làn dành riêng cho xe buýt 2 hướng (trái+thẳng)", "Làn kết hợp cho xe buýt."),
    "R.404e": ("Làn dành riêng cho xe buýt 2 hướng (thẳng+phải)", "Làn xe buýt thẳng và rẽ phải."),
    "R.404f": ("Làn dành riêng cho xe buýt 3 hướng", "Làn xe buýt đa hướng."),
    "R.404g": ("Làn dành riêng cho xe buýt (trái+phải)", "Làn xe buýt rẽ 2 hướng."),
    "R.404h": ("Làn dành riêng cho xe buýt (phức hợp)", "Làn xe buýt chuyên dụng."),
    "R.404k": ("Làn dành riêng cho xe buýt (phức hợp nâng cao)", "Tuân thủ quy định làn xe buýt."),
    "R.411": ("Hướng đi trên mỗi làn đường phải theo", "Đi đúng làn đường theo mũi tên chỉ dẫn."),
    "R.415a": ("Biển gộp làn đường theo phương tiện (dạng a)", "Mỗi làn dành cho loại xe cụ thể."),
    "R.415b": ("Biển gộp làn đường theo phương tiện (dạng b)", "Mỗi làn dành cho loại xe cụ thể."),
    "R.420": ("Bắt đầu khu đông dân cư", "Bắt đầu khu dân cư, giảm tốc và chú ý người đi bộ."),
    "R.421": ("Hết khu đông dân cư", "Hết khu dân cư, có thể tăng tốc theo quy định."),
    "R.E,10a": ("Phần đường xe hai bánh rẽ trái qua nút giao", "Xe hai bánh rẽ trái theo phần đường chỉ định."),
    "R.E,10b": ("Phần đường xe hai bánh rẽ phải qua nút giao", "Xe hai bánh rẽ phải theo phần đường chỉ định."),
    "R.E,10c": ("Phần đường xe hai bánh đi thẳng qua nút giao", "Xe hai bánh đi thẳng theo phần đường chỉ định."),
    "R.E,10d": ("Phần đường xe hai bánh phức hợp qua nút giao", "Xe hai bánh đi theo chỉ dẫn tại nút giao."),
    "R.E,11a": ("Vạch dừng xe cho xe hai bánh bên trái", "Xe hai bánh dừng đúng vạch bên trái khi đèn đỏ."),
    "R.E,11b": ("Vạch dừng xe cho xe hai bánh bên phải", "Xe hai bánh dừng đúng vạch bên phải khi đèn đỏ."),
    "R.E,9a": ("Nơi dừng xe buýt bên phải phía trước", "Trạm xe buýt bên phải, xe khác không đỗ chắn trạm."),
    "R.E,9b": ("Nơi dừng xe buýt bên trái phía trước", "Trạm xe buýt bên trái, không đỗ xe chắn trạm."),
    "R.E,9c": ("Nơi dừng xe buýt bên phải phía sau", "Trạm xe buýt phía sau bên phải."),
    "R.E,9d": ("Nơi dừng xe buýt bên trái phía sau", "Trạm xe buýt phía sau bên trái."),

    # === BIỂN CẢNH BÁO (W) - ĐÃ KIỂM CHỨNG TOÀN BỘ ===
    "W.201a": ("Chỗ ngoặt nguy hiểm vòng bên trái", "Giảm tốc, bám vô lăng và không vượt xe tại khúc cua."),
    "W.201b": ("Chỗ ngoặt nguy hiểm vòng bên phải", "Giảm tốc, bám sát lề đường và không vượt."),
    "W.201c": ("Chỗ ngoặt nguy hiểm có nguy cơ lật xe (vòng trái)", "Giảm tốc triệt để, xe tải dễ bị lật."),
    "W.201d": ("Chỗ ngoặt nguy hiểm có nguy cơ lật xe (vòng phải)", "Giảm tốc triệt để, xe bus đặc biệt chú ý."),
    "W.202a": ("Nhiều chỗ ngoặt liên tiếp (vòng trái trước)", "Nhiều khúc cua liên tục, giảm tốc và tập trung."),
    "W.202b": ("Nhiều chỗ ngoặt liên tiếp (vòng phải trước)", "Nhiều cua liên tục, giữ tốc độ thấp."),
    "W.203a": ("Đường bị thu hẹp cả hai bên", "Đường hẹp, giảm tốc và nhường xe ngược chiều."),
    "W.203b": ("Đường bị thu hẹp về bên trái", "Đường hẹp bên trái, đi sát bên phải."),
    "W.203c": ("Đường bị thu hẹp về bên phải", "Đường hẹp bên phải, giảm tốc."),
    "W.204": ("Đường hai chiều", "Đường một chiều chuyển sang hai chiều, đi đúng phần đường bên phải."),
    "W.205a": ("Giao nhau các đường cùng cấp (ngã tư)", "Ngã tư phía trước, giảm tốc, nhường đường bên phải."),
    "W.205c": ("Giao nhau các đường cùng cấp (chữ Y)", "Ngã ba chữ Y, giảm tốc và quan sát."),
    "W.205d": ("Giao nhau các đường cùng cấp (chữ T)", "Ngã ba chữ T, giảm tốc."),
    "W.205e": ("Giao nhau các đường cùng cấp (dạng khác)", "Nút giao, giảm tốc và quan sát."),
    "W.206": ("Giao nhau chạy theo vòng xuyến", "Phía trước có vòng xuyến, giảm tốc."),
    "W.207a": ("Giao nhau với đường không ưu tiên (nhánh phải)", "Ngã ba có nhánh phải, chú ý xe nhập vào."),
    "W.207b": ("Giao nhau với đường không ưu tiên (nhánh trái)", "Ngã ba có nhánh trái, chú ý xe nhập vào."),
    "W.207c": ("Giao nhau với đường không ưu tiên (ngã tư)", "Ngã tư, bạn trên đường ưu tiên nhưng vẫn quan sát."),
    "W.207d": ("Giao nhau với đường không ưu tiên (nhánh phải chéo)", "Nhánh phải chéo nhập vào, chú ý."),
    "W.207e": ("Giao nhau với đường không ưu tiên (nhánh trái chéo)", "Nhánh trái chéo nhập vào, chú ý."),
    "W.207f": ("Giao nhau với đường không ưu tiên (chữ T ngược)", "Ngã ba chữ T ngược, giảm tốc."),
    "W.207g": ("Giao nhau với đường không ưu tiên (chữ T phải)", "Ngã ba chữ T phải, chú ý xe nhánh phải."),
    "W.207h": ("Giao nhau với đường không ưu tiên (chữ T trái)", "Ngã ba chữ T trái, chú ý xe nhánh trái."),
    "W.207i": ("Giao nhau với đường không ưu tiên (chữ Y)", "Ngã ba chữ Y, giảm tốc."),
    "W.207j": ("Giao nhau với đường không ưu tiên (chữ Y phải)", "Chú ý xe từ nhánh phải."),
    "W.207k": ("Giao nhau với đường không ưu tiên (chữ Y trái)", "Chú ý xe từ nhánh trái."),
    "W.207l": ("Giao nhau với đường không ưu tiên (vòng xuyến)", "Vòng xuyến phía trước, giảm tốc."),
    "W.207m": ("Giao nhau với đường không ưu tiên (phức hợp)", "Nút giao phức hợp, quan sát cẩn thận."),
    "W.208": ("Giao nhau với đường ưu tiên", "Phải nhường đường cho xe trên đường ưu tiên."),
    "W.209": ("Giao nhau có tín hiệu đèn", "Phía trước có đèn giao thông, chuẩn bị giảm tốc."),
    "W.210": ("Giao nhau với đường sắt có rào chắn", "Giao cắt đường sắt có rào chắn, dừng khi rào hạ."),
    "W.211": ("Giao nhau với đường sắt không có rào chắn", "Cực kỳ nguy hiểm, phải dừng hẳn và quan sát."),
    "W.212": ("Cầu hẹp", "Cầu hẹp phía trước, nhường xe ngược chiều."),
    "W.213": ("Cầu tạm", "Cầu tạm phía trước, giảm tốc và đi cẩn thận."),
    "W.214": ("Cầu quay, cầu cất", "Phía trước có cầu quay, dừng khi cầu mở cho tàu."),
    "W.215a": ("Kè, vực sâu phía trước", "Phía trước có kè/vực sâu, giảm tốc."),
    "W.215b": ("Kè, vực sâu bên phải đường", "Bên phải là vực sâu, bám sát bên trái."),
    "W.215c": ("Kè, vực sâu bên trái đường", "Bên trái là vực sâu, bám sát bên phải."),
    "W.216a": ("Đường ngầm (nước chảy qua đường)", "Đường ngập nước, giảm tốc tối đa khi qua."),
    "W.216b": ("Đường ngầm có nguy cơ lũ quét", "Cực kỳ nguy hiểm khi mưa, không qua nếu nước lớn."),
    "W.217": ("Bến phà", "Phía trước có bến phà, giảm tốc và xếp hàng."),
    "W.218": ("Cửa chui (cổng chắn ngang đường)", "Phía trước có cổng chui hoặc cầu vượt thấp, chú ý chiều cao xe."),
    "W.219": ("Dốc xuống nguy hiểm", "Đoạn dốc xuống nguy hiểm, giảm số hãm phanh động cơ."),
    "W.220": ("Dốc lên nguy hiểm", "Đoạn dốc lên nguy hiểm, giảm số tăng lực kéo."),
    "W.221a": ("Đường không bằng phẳng có ổ gà, lồi lõm", "Mặt đường xấu, gồ ghề, giảm tốc."),
    "W.221b": ("Đường có gồ giảm tốc", "Phía trước có gồ giảm tốc, giảm tốc ngay."),
    "W.222a": ("Đường trơn", "Mặt đường trơn, giảm tốc và giữ khoảng cách."),
    "W.222b": ("Lề đường nguy hiểm", "Lề đường yếu, không đi sát mép đường."),
    "W.223a": ("Vách núi nguy hiểm (bên phải)", "Nguy hiểm vách núi sạt lở bên phải, đi nhanh qua."),
    "W.223b": ("Vách núi nguy hiểm (bên trái)", "Nguy hiểm vách núi sạt lở bên trái, đi nhanh qua."),
    "W.224": ("Đường người đi bộ cắt ngang", "Phía trước có vạch qua đường, giảm tốc và nhường đường."),
    "W.225": ("Trẻ em (gần trường học)", "Gần trường học, trẻ em hay qua đường, cực kỳ cẩn thận."),
    "W.226": ("Đường xe đạp cắt ngang", "Phía trước có xe đạp hay cắt ngang, giảm tốc."),
    "W.227": ("Công trường (đường đang thi công)", "Đường đang thi công, giảm tốc."),
    "W.228a": ("Đá lở (sụt lở bên phải)", "Nguy cơ đá rơi bên phải, đi nhanh qua."),
    "W.228b": ("Đá lở (sụt lở bên trái)", "Nguy cơ đá rơi bên trái, đi nhanh qua."),
    "W.228c": ("Sỏi đá bắn lên", "Mặt đường rời rạc, sỏi đá bắn lên gây nguy hiểm."),
    "W.228d": ("Nền đường yếu", "Nền đường yếu, giảm tốc."),
    "W.229": ("Dải máy bay lên xuống", "Đường cát ngang hướng máy bay hạ cánh, chú ý trên không."),
    "W.230": ("Gia súc qua đường", "Khu vực có gia súc thả rông, giảm tốc."),
    "W.231": ("Thú rừng qua đường", "Khu vực rừng có thú hoang, lái chậm."),
    "W.232": ("Gió ngang mạnh", "Gió ngang mạnh, giữ chắc vô lăng và giảm tốc."),
    "W.233": ("Nguy hiểm khác", "Có nguy hiểm không xác định, lái xe cẩn thận."),
    "W.234": ("Giao nhau với đường hai chiều", "Trên đường một chiều sắp giao đường hai chiều."),
    "W.235": ("Đường đôi (có dải phân cách)", "Phía trước có dải phân cách, đi đúng phần đường."),
    "W.236": ("Hết đường đôi (hết dải phân cách)", "Hết dải phân cách, chú ý xe ngược chiều."),
    "W.237": ("Cầu vồng (đường có độ vồng lớn)", "Đoạn vồng lớn hạn chế tầm nhìn, giảm tốc."),
    "W.238": ("Đường cao tốc phía trước", "Sắp vào đường cao tốc, chuẩn bị tăng tốc."),
    "W.239a": ("Đường cáp điện ở phía trên", "Dây điện cao thế phía trên, xe cao chú ý chiều cao."),
    "W.239b": ("Đường cáp điện ở phía trên (dạng khác)", "Dây điện phía trên, chú ý chiều cao xe."),
    "W.240": ("Đường hầm", "Sắp vào hầm, bật đèn và giảm tốc."),
    "W.241": ("Ùn tắc giao thông", "Đoạn đường hay ùn tắc, chuẩn bị dừng."),
    "W.242a": ("Nơi đường sắt giao vuông góc (1 ray)", "Giao cắt đường sắt 1 ray, dừng hẳn quan sát."),
    "W.242b": ("Nơi đường sắt giao vuông góc (nhiều ray)", "Giao cắt đường sắt nhiều ray, dừng hẳn quan sát."),
    "W.243a": ("Nơi đường sắt giao không vuông góc (1 ray)", "Giao cắt chéo đường sắt, cực kỳ cẩn thận."),
    "W.243b": ("Nơi đường sắt giao không vuông góc (nhiều ray)", "Giao cắt chéo nhiều ray, dừng hẳn quan sát."),
    "W.243c": ("Nơi đường sắt giao không vuông góc (dạng khác)", "Giao cắt chéo đường sắt, dừng hẳn quan sát."),
    "W.244": ("Đoạn đường hay xảy ra tai nạn", "Đoạn đường hay tai nạn, tập trung lái xe, giảm tốc."),
    "W.245a": ("Đi chậm", "Yêu cầu giảm tốc độ."),
    "W.245b": ("Đi chậm (có tiếng Anh)", "Slow down - Giảm tốc ngay."),
    "W.246a": ("Chướng ngại vật vòng tránh hai bên", "Có chướng ngại vật, vòng trái hoặc phải."),
    "W.246b": ("Chướng ngại vật vòng tránh sang trái", "Có chướng ngại vật, chỉ vòng sang trái."),
    "W.246c": ("Chướng ngại vật vòng tránh sang phải", "Có chướng ngại vật, chỉ vòng sang phải."),
}

def main():
    df = pd.read_csv(METADATA_PATH)
    print(f"Loaded: {len(df)} rows")
    updated = 0
    not_found = set()
    for idx, row in df.iterrows():
        label = str(row.get('label', ''))
        if label in SIGN_DATA:
            m, a = SIGN_DATA[label]
            df.at[idx, 'meaning'] = m
            df.at[idx, 'advice'] = a
            updated += 1
        else:
            not_found.add(label)
    df.to_csv(METADATA_PATH, index=False)
    print(f"Updated: {updated} rows")
    if not_found:
        print(f"NOT in dict ({len(not_found)}): {sorted(not_found)}")
    else:
        print("All labels updated!")

if __name__ == "__main__":
    main()
